name: Deploy to Cloud Run (Dev)

on:
  push:
    branches:
      - main

env:
  REGION: asia-southeast2 
  SERVICE_NAME: askr-frontend
  IMAGE: asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_DEV }}/askr-repo/askr-frontend:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER_DEV }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT_DEV }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker push
        run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL="${{ secrets.NEXT_PUBLIC_API_URL_DEV }}" \
            --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY_DEV }}" \
            --build-arg NEXT_PUBLIC_CLERK_SIGN_IN_URL="/auth/sign-in" \
            --build-arg NEXT_PUBLIC_CLERK_SIGN_UP_URL="/auth/sign-up" \
            --build-arg NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL="/workspaces" \
            --build-arg NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL="/workspaces" \
            --build-arg NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL="/workspaces" \
            --build-arg NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL="/workspaces" \
            -t ${{ env.IMAGE }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE }}
          flags: --allow-unauthenticated
